
#set the value of the GOTTY_CREDENTIAL  env variable
#secret:
#  value: "user01:password01"

#set the value of the GOTTY_CREDENTIAL_FILE variable
#Set the path of the file where credentials are stored
secretFile:
  path: "test_webkubectl_credentials.txt"

#Add other env variables in the extraEnv
#Do not set the GOTTY_CREDENTIAL_FILE in the extraEnv  
extraEnv:
  GOTTY_TEST_1: value_test_1
  GOTTY_TEST_2: value_test_2
  GOTTY_TEST_3: value_test_3
  
#You can additionally add the GOTTY_OPTIONS env variable and set the others env variable as command line options
#GOTTY_OPTIONS : "--port 8080 --permit-write --permit-arguments --credential user01:password01"
  