apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webkubectl.fullname" . }}
data:
  credentials.conf: |-
  {{- if .Values.secretFile }}
  {{ .Files.Get .Values.secretFile.path | nindent 4}}
  {{- end }}